name: Send Slack Notification

on:
  pull_request_review_comment:
    types: [created]

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
      - name: Install Slack Ruby Gem
        run: gem install slack-ruby-client

      - name: Send Slack Notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: ruby send_slack_notification.rb
