name: Notify on Slack for PR Comments
on:
  issue_comment:
    types: [created]
jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Send Slack notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: <your-slack-channel-id>
        run: |
          ruby send_slack_notification.rb ${{ github.event.issue.number }} "${{ github.event.comment.body }}"
