name: Slack Notification for PR Review Request

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'open'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1

      - name: Install Slack Ruby Gem
        run: gem install slack-ruby-client

      - name: Get reviewer email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REVIEWER_LOGIN=$(echo '${{ github.event.review.user.login }}' | tr -d '[:space:]')
          
          REVIEWER_EMAIL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/users/$REVIEWER_LOGIN" | jq -r '.email')
          
          echo "Reviewer email: $REVIEWER_EMAIL"


      - name: Send Slack Notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          REQUESTED_REVIEWER: ${{ github.event.requested_reviewer.login }}
        run: ruby pull_request_notification.rb
