name: Slack Notification for PR Review Request

on:
  pull_request_review_requested:
    types: [review_requested]

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1

      - name: Install Slack Ruby Gem
        run: gem install slack-ruby-client

      - name: Send Slack Notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          REQUESTED_REVIEWER: ${{ github.event.requested_reviewer.login }}
        run: ruby send_slack_notification.rb
